version: "3"

services:
  web:
    image: jmalloc/echo-server
 
  haproxy:
    image: haproxytech/haproxy-alpine:2.4
    ports:
      - 80:80
      - "8404:8404"
    volumes: 
      - "./config:/usr/local/etc/haproxy:ro"
    depends_on:
      - web
    